name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
       DISPLAY: :0 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
          pip install sphinx sphinx_rtd_theme myst_parser mediapipe tk opencv-python customtkinter mouse pillow pyautogui
          sudo apt-get install python3-tk
          touch ~/.Xauthority
          # Generate the magic cookie with 128 bit hex encoding
          xauth add ${HOST}:0 . $(xxd -l 16 -p /dev/urandom)
      - name: Sphinx build
        run: |
          cd Docs/
          sphinx-apidoc -o ./source .. -f
          make html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Docs/build/html
          force_orphan: true
